# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
i=1
sum=2
a1=1
a2=2
a3=0
for i in range(1,10-2):
 a3=a1+a2
 a1=a2
 a2=a3
 if(a3%2==0):
   sum=sum+a3
print sum

